default: &default
  host: localhost
  adapter: postgresql
  encoding: UTF8
  username: expert
  timeout: 5000
  reaping_frequency: 30

development:
  <<: *default
  database: expert_development
  password: <%= Rails.application.secrets[:database][:password] %>

test:
  <<: *default
  database: expert_test
  password: <%= Rails.application.secrets[:database][:password] %>

production:
  <<: *default
  database: expert_production
  password: <%= ENV['EXERCISE_DATABASE_PASSWORD'] %>